name: NoRegionWindCharges
main: me.imsonulucky.noregionwindcharges.NoRegionWindCharges
version: 1.0
api-version: 1.21
depend: [WorldGuard]
commands:
  nrw:
    description: Reloads the config
    usage: /nrw reload
    permission: noregionwindcharges.reload
permissions:
  noregionwindcharges.reload:
    default: op
